Type: "AWS::DynamoDB::Table"
Properties:
  TableName: ${self:custom.prjPrefix}-category
  AttributeDefinitions:
    - AttributeName: cateId
      AttributeType: N
    - AttributeName: contentDiv
      AttributeType: S
    - AttributeName: parentPath
      AttributeType: S
    - AttributeName: contentDivSlug
      AttributeType: S
  KeySchema:
    - AttributeName: cateId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.category.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.category.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.category.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    - IndexName: ContentDivParentPath_idx
      KeySchema:
        - AttributeName: contentDiv
          KeyType: HASH
        - AttributeName: parentPath
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
    - IndexName: ContentDivSlug_idx
      KeySchema:
        - AttributeName: contentDivSlug
          KeyType: HASH
      Projection:
        ProjectionType: ALL
