Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-event
  AttributeDefinitions:
    -
      AttributeName: eventId
      AttributeType: S
    -
      AttributeName: fieldIdDate
      AttributeType: S
    -
      AttributeName: createdAt
      AttributeType: S
  KeySchema:
    -
      AttributeName: eventId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.event.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.event.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.event.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: fieldIdDateNumberIndex
      KeySchema:
      -
        AttributeName: fieldIdDate
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
