Type: "AWS::DynamoDB::Table"
Properties:
  TableName: ${self:custom.prjPrefix}-field
  AttributeDefinitions:
    - AttributeName: fieldId
      AttributeType: S
    - AttributeName: slug
      AttributeType: S
    - AttributeName: categoryContentDiv
      AttributeType: S
    - AttributeName: categoryRegionPathSlug
      AttributeType: S
  KeySchema:
    - AttributeName: fieldId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.field.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.field.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.field.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    - IndexName: slug_idx
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
      Projection:
        ProjectionType: ALL
    - IndexName: categoryRegionParentPath_idx
      KeySchema:
        - AttributeName: categoryContentDiv
          KeyType: HASH
        - AttributeName: categoryRegionPathSlug
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
