Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-field
  AttributeDefinitions:
    -
      AttributeName: fieldId
      AttributeType: S
  KeySchema:
    -
      AttributeName: fieldId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.field.billingMode}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.field.provisionedThroughput.readCapacityUnits}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.field.provisionedThroughput.writeCapacityUnits}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}
