Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-game-user
  AttributeDefinitions:
    -
      AttributeName: gameUserId
      AttributeType: S
    -
      AttributeName: gameId
      AttributeType: S
    #-
    #  AttributeName: userId
    #  AttributeType: S
    -
      AttributeName: createdAt
      AttributeType: S
  KeySchema:
    -
      AttributeName: gameUserId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.gameUser.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.gameUser.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.gameUser.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: gameIdIndex
      KeySchema:
      -
        AttributeName: gameId
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
