Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-game
  AttributeDefinitions:
    -
      AttributeName: gameId
      AttributeType: S
    -
      AttributeName: eventId
      AttributeType: S
    -
      AttributeName: gameNumber
      AttributeType: N
  KeySchema:
    -
      AttributeName: gameId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.game.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.game.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.game.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: eventIdIndex
      KeySchema:
      -
        AttributeName: eventId
        KeyType: HASH
      -
        AttributeName: gameNumber
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
