Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-post-tag
  AttributeDefinitions:
    -
      AttributeName: postId
      AttributeType: S
    -
      AttributeName: tagId
      AttributeType: S
    -
      AttributeName: statusPublishAt
      AttributeType: S
  KeySchema:
    -
      AttributeName: postId
      KeyType: HASH
    -
      AttributeName: tagId
      KeyType: RANGE

  BillingMode: ${self:custom.dynamodbConfig.postTag.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.postTag.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.postTag.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: postsByTagGsi
      KeySchema:
      -
        AttributeName: tagId
        KeyType: HASH
      -
        AttributeName: statusPublishAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
      #BillingMode: PAY_PER_REQUEST
      #ProvisionedThroughput:
      #  ReadCapacityUnits: 5
      #  WriteCapacityUnits: 3
