
Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-user-event
  AttributeDefinitions:
    -
      AttributeName: userIdEventId
      AttributeType: S
    -
      AttributeName: userId
      AttributeType: S
    -
      AttributeName: eventId
      AttributeType: S
    -
      AttributeName: createdAt
      AttributeType: S
  KeySchema:
    -
      AttributeName: userIdEventId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.eventUser.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.eventUser.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.eventUser.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: userIdIndex
      KeySchema:
      -
        AttributeName: userId
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
    -
      IndexName: eventIdIndex
      KeySchema:
      -
        AttributeName: eventId
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
