Type: 'AWS::DynamoDB::Table'
Properties:
  TableName: ${self:custom.prjPrefix}-user-game
  AttributeDefinitions:
    -
      AttributeName: userIdGameId
      AttributeType: S
    -
      AttributeName: gameId
      AttributeType: S
    -
      AttributeName: userId
      AttributeType: S
    -
      AttributeName: userIdEventId
      AttributeType: S
    -
      AttributeName: createdAt
      AttributeType: S
  KeySchema:
    -
      AttributeName: userIdGameId
      KeyType: HASH

  BillingMode: ${self:custom.dynamodbConfig.userGame.billingMode, 'PAY_PER_REQUEST'}
  ProvisionedThroughput:
    ReadCapacityUnits: ${self:custom.dynamodbConfig.userGame.provisionedThroughput.readCapacityUnits, 0}
    WriteCapacityUnits: ${self:custom.dynamodbConfig.userGame.provisionedThroughput.writeCapacityUnits, 0}

  Tags:
    - Key: backup
      Value: ${self:custom.dynamoDbBackupTargetTagValue}

  GlobalSecondaryIndexes:
    -
      IndexName: userIdIndex
      KeySchema:
      -
        AttributeName: userId
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
    -
      IndexName: gameIdIndex
      KeySchema:
      -
        AttributeName: gameId
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
    -
      IndexName: userIdEventIdIndex
      KeySchema:
      -
        AttributeName: userIdEventId
        KeyType: HASH
      -
        AttributeName: createdAt
        KeyType: RANGE
      Projection:
        ProjectionType: ALL
